baseurl = "http://localhost:1313"
title = "MR J - Blog"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "MR J"
    info = ""
    description = "张梦金的日常开发随笔博客"
    keywords = "blog,go,golang,docker,k8s,微服务"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "coding 给我无限的乐趣."

    hidecredits = false
    hidecopyright = true

    rtl = false

    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/clearcodecn/"

# Menu links

[[menu.main]]
    name = "博客"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "微服务"
    weight = 2
    url  = "/microservices/"
#[[menu.main]]
 #   name = "关于"
 #   weight = 2
 #   url = "/about/"